export const GET_DEVICE_SUCCESS = "DEVICES/GET_DEVICE_SUCCESS";
export const BACK_TO_DEVICE_SELECTION = "DEVICES/BACK_TO_DEVICE_SELECTION";
export const DEVICE_CHARACTERISTIC_CHANGE_RECEIVED = "DEVICES/DEVICE_CHARACTERISTIC_CHANGE_RECEIVED";